import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, realpath, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { invokeCliProcess, validateRepositoryDirectory } from '../apps/desktop/electron/cli-runner.mjs';
import { workspaceLandingPage } from '../apps/desktop/src/workspace-routing.mjs';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('Electron repository validation explains invalid and uninitialized selections', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'sflow-electron-repository-'));
  await assert.rejects(() => validateRepositoryDirectory(root), /not a Git repository/);
  const initialized = spawnSync('git', ['init', '-b', 'main'], { cwd: root, encoding: 'utf8' });
  assert.equal(initialized.status, 0, initialized.stderr);
  await assert.rejects(() => validateRepositoryDirectory(root), /not initialized with Singularity Flow/);
  await mkdir(path.join(root, '.singularity'));
  await writeFile(path.join(root, '.singularity', 'workflow.yml'), 'version: 1\n');
  await assert.rejects(
    () => validateRepositoryDirectory(root),
    (error) => error.code === 'SINGULARITY_FLOW_LEGACY_CONTROL_ROOT' && error.legacyRoot === '.singularity'
  );
  await mkdir(path.join(root, 'singularity'));
  await writeFile(path.join(root, 'singularity', 'workflow.yml'), 'version: 1\n');
  assert.equal(await validateRepositoryDirectory(root), await realpath(root));
});

test('Electron repository validation canonicalizes aliases and rejects fake Git or symlinked control paths', async () => {
  const fake = await mkdtemp(path.join(os.tmpdir(), 'sflow-electron-fake-git-'));
  await mkdir(path.join(fake, '.git'));
  await mkdir(path.join(fake, 'singularity'));
  await writeFile(path.join(fake, 'singularity', 'workflow.yml'), 'version: 1\n');
  await assert.rejects(() => validateRepositoryDirectory(fake), /not a valid Git working tree/);

  const root = await mkdtemp(path.join(os.tmpdir(), 'sflow-electron-canonical-'));
  assert.equal(spawnSync('git', ['init', '-b', 'main'], { cwd: root }).status, 0);
  const external = await mkdtemp(path.join(os.tmpdir(), 'sflow-electron-external-'));
  await writeFile(path.join(external, 'workflow.yml'), 'version: 1\n');
  await symlink(external, path.join(root, 'singularity'), 'dir');
  await assert.rejects(() => validateRepositoryDirectory(root), /control directory cannot be a symbolic link/);

  const safe = await mkdtemp(path.join(os.tmpdir(), 'sflow-electron-safe-'));
  assert.equal(spawnSync('git', ['init', '-b', 'main'], { cwd: safe }).status, 0);
  await mkdir(path.join(safe, 'singularity'));
  await writeFile(path.join(safe, 'singularity', 'workflow.yml'), 'version: 1\n');
  const alias = `${safe}-alias`;
  await symlink(safe, alias, 'dir');
  assert.equal(await validateRepositoryDirectory(alias), await realpath(safe));
});

test('Electron CLI runner returns JSON and bounds a stuck child process', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'sflow-electron-runner-'));
  const fixture = path.join(root, 'fixture.mjs');
  await writeFile(fixture, `
if (process.argv[2] === 'wait') setInterval(() => {}, 1000);
else process.stdout.write(JSON.stringify({ opened: process.cwd() }));
`);
  const opened = await invokeCliProcess({ executable: process.execPath, cli: fixture, repository: root, args: ['open'], env: process.env, timeoutMs: 1000 });
  assert.equal(await realpath(opened.opened), await realpath(root));
  await assert.rejects(
    () => invokeCliProcess({ executable: process.execPath, cli: fixture, repository: root, args: ['wait'], env: process.env, timeoutMs: 50 }),
    /did not finish within 1 seconds/
  );
});

test('Electron welcome screen opens the workspace boundary and preserves loading feedback', async () => {
  const source = await readFile(path.join(packageRoot, 'apps/desktop/src/App.jsx'), 'utf8');
  assert.match(source, /Opening workspace…/);
  assert.match(source, /Open project workspace/);
  assert.match(source, /workspace carries every repository and its Jira routing/);
  assert.match(source, /Opening the selected project context/);
  assert.match(source, /Open or create workspace/);
  assert.match(source, /Workspace configuration/);
  assert.match(source, /\{ id: 'workspaces', label: 'Workspace setup', section: 'Project setup' \}/);
  assert.match(source, /acceptOpened\(result, workspaceLandingPage\(result, experienceMode\)\)/);
  assert.match(source, /if \(result\.profile\.workspacePath\) await openWorkspace\(result\.profile\.workspacePath\)/);
  assert.doesNotMatch(source, /firstRepository/);
  assert.match(source, /defaultBaseDirectory=\{data\.workspaceSetup\?\.baseDirectory/);
  assert.match(source, /if \(!data\).*<Toast toast=\{toast\}/s);
  assert.doesNotMatch(source, /finally \{ setBusy\(false\); setTimeout\(\(\) => setToast\(null\)/);
});

test('Electron routes new workspace selections to configuration before Epic intake', () => {
  assert.equal(workspaceLandingPage({ workspaceSetup: { mode: 'create' } }, 'business'), 'workspaces');
  assert.equal(workspaceLandingPage({ workspaceSetup: { mode: 'create' } }, 'engineer'), 'workspaces');
  assert.equal(workspaceLandingPage({ workspace: { workspace: { id: 'existing' } } }, 'business'), 'epics');
  assert.equal(workspaceLandingPage({ workspace: { workspace: { id: 'existing' } } }, 'engineer'), 'workspaces');
});

test('Electron Epic start remains usable without an existing portfolio and renderer failures stay recoverable', async () => {
  const source = await readFile(path.join(packageRoot, 'apps/desktop/src/App.jsx'), 'utf8');
  const entrypoint = await readFile(path.join(packageRoot, 'apps/desktop/src/main.jsx'), 'utf8');
  assert.match(source, /data\.portfolio\?\.initiativeProfiles \?\? \{/);
  assert.match(source, /Epic planning initialized from the repository defaults/);
  assert.match(source, /Initialize governed Epic planning/);
  assert.match(source, /No separate portfolio setup is required/);
  assert.match(source, /Local Epic creation starts from a clean/);
  assert.doesNotMatch(source, /Object\.entries\(data\.portfolio\.initiativeProfiles\)/);
  assert.match(entrypoint, /class DesktopErrorBoundary extends React\.Component/);
  assert.match(entrypoint, /This screen could not finish loading/);
  assert.match(entrypoint, /window\.location\.reload\(\)/);
});

test('Electron onboarding fails closed with a recoverable retry screen', async () => {
  const source = await readFile(path.join(packageRoot, 'apps/desktop/src/App.jsx'), 'utf8');
  const main = await readFile(path.join(packageRoot, 'apps/desktop/electron/main.mjs'), 'utf8');
  assert.match(source, /function OnboardingLoadFailure/);
  assert.match(source, /We stopped before opening your workspace/);
  assert.match(source, /No repository, Jira, or Git state was changed/);
  assert.match(source, /The secure desktop bridge is unavailable/);
  assert.match(source, /setOnboardingAttempt\(\(current\) => current \+ 1\)/);
  assert.match(source, /Advanced setup remains available later/);
  assert.match(source, /Local workspaces/);
  assert.match(source, /Jira connection/);
  assert.match(source, /result\.notices\?\.length/);
  assert.doesNotMatch(source, /if \(saved\) setDraft\(\(current\) => \(\{ \.\.\.current, step: nextStep \}\)\)/);
  assert.match(main, /prepareOnboardingProfile/);
  assert.match(main, /notices: prepared\.notices/);
  assert.doesNotMatch(source, /setOnboarding\(\{ profile: \{ completed: true \}/);
});

test('Electron desktop exposes guided workflow and portable repository configuration controls', async () => {
  const source = await readFile(path.join(packageRoot, 'apps/desktop/src/App.jsx'), 'utf8');
  const navigation = source.slice(source.indexOf('const engineerNavSections'), source.indexOf('const onboardingRoles'));
  const styles = await readFile(path.join(packageRoot, 'apps/desktop/src/styles.css'), 'utf8');
  const preload = await readFile(path.join(packageRoot, 'apps/desktop/electron/preload.cjs'), 'utf8');
  const main = await readFile(path.join(packageRoot, 'apps/desktop/electron/main.mjs'), 'utf8');
  const indexHtml = await readFile(path.join(packageRoot, 'apps/desktop/index.html'), 'utf8');
  const artifactBuilder = await readFile(path.join(packageRoot, 'apps/desktop/src/artifact-builder.mjs'), 'utf8');
  assert.match(source, />＋ Workflow</);
  assert.match(source, />＋ New stage</);
  assert.match(source, /Artifact path/);
  assert.match(source, /Inputs from earlier stages/);
  assert.match(source, /Copilot session policy/);
  assert.match(source, /Block mutating tools until both selections complete/);
  assert.match(source, /Create artifact template/);
  assert.match(source, /Create persona and prompt/);
  assert.match(source, /Create repository skill/);
  assert.match(source, /Repository-owned world model/);
  assert.match(source, /Editable builder prompt/);
  assert.match(source, /World-model views/);
  assert.match(source, /referenced view cannot be removed/i);
  assert.match(styles, /Avenir Next/);
  assert.match(styles, /Iowan Old Style/);
  assert.match(styles, /color-scheme: light/);
  assert.match(styles, /--navy-950/);
  assert.match(styles, /background: #181817/);
  assert.match(styles, /border-radius: 999px/);
  assert.match(styles, /body \{[^}]*font-size: 15px/s);
  assert.match(source, /fontSize: 14/);
  assert.doesNotMatch(source, /className="publish-scope-notice"/);
  assert.doesNotMatch(styles, /\.publish-scope-notice/);
  assert.match(source, />Download config</);
  assert.match(source, /Approval inbox/);
  assert.match(source, /Initiative orchestration/);
  assert.match(source, /Advanced governance/);
  assert.match(source, /Cross-repository control plane/);
  assert.match(source, /Set up your Epic workspace/);
  assert.match(source, /Create & validate governance/);
  assert.match(source, /Set your working perspective/);
  assert.match(source, /Advanced setup/);
  assert.match(source, /Local workspace/);
  assert.match(source, /Workspace repositories/);
  assert.match(source, /Lead and participating repositories/);
  assert.match(source, /Jira connection/);
  assert.match(source, /Continue to Flow/);
  assert.match(source, /Local setup recovered/);
  assert.match(source, /Application ID/);
  assert.match(source, /Additional metadata/);
  assert.match(source, /Add a participating repository/);
  assert.match(source, /Add to YAML draft/);
  assert.match(source, /No credentials are stored in Git/);
  assert.match(source, /Assurance & freshness/);
  assert.match(source, /Repository delivery graph/);
  assert.match(source, /Epic-level story progress/);
  assert.match(source, /Epic lifecycle wizard/);
  assert.match(source, /Turn an Epic into delivery-ready Stories/);
  assert.match(source, /className="epic-start-intro-copy"/);
  assert.match(source, /aria-label="Epic planning workflow"/);
  assert.match(source, /const epicJourneySteps = \['Sources', 'Requirements', 'Planning', 'Stories', 'Complete'\]/);
  assert.match(source, /function EpicJourneyDiagram\(\{ activeStep = 0 \}\)/);
  assert.match(source, /<EpicJourneyDiagram activeStep=\{businessStage\.activeStep\} \/>/);
  assert.match(source, /activeStep: 1/);
  assert.match(source, /activeStep: 2/);
  assert.match(source, /!entryTab && <nav className="epic-lifecycle-wizard"/);
  assert.match(source, /Bring from Jira/);
  assert.match(source, /Set up Jira →/);
  assert.match(source, /Connect Jira to bring in Epics/);
  assert.match(source, /Save Jira policy & continue/);
  assert.match(source, /function JiraPolicySetup/);
  assert.match(source, /Save policy & enter credentials/);
  assert.match(source, /Initialize governed Jira access/);
  assert.match(source, /Configure governed Jira access/);
  assert.match(source, /singularity:setup-jira/);
  assert.match(source, /className="jira-setup-overlay"/);
  assert.doesNotMatch(source, /disabled=\{!data\.portfolio\?\.jira\?\.enabled\}/);
  assert.match(source, /Describe the work/);
  assert.match(source, /const businessNavSections/);
  assert.match(source, /\['epics', 'Epics'\]/);
  assert.match(source, /\['inbox', 'Reviews'\]/);
  assert.match(source, /Sources/);
  assert.match(source, /PhaseGovernance/);
  assert.match(source, /generated User Stories/);
  assert.match(source, /High-level solution specification/);
  assert.match(source, /Select what Jira receives/);
  assert.match(source, /Spec-to-code completion/);
  assert.match(source, /Pinned source versions/);
  assert.match(source, /Exact Jira Story and artifact plan/);
  assert.match(source, /Story review inbox/);
  assert.match(source, /Run and record exact-SHA checks/);
  assert.match(source, /Local role/);
  assert.match(source, /Jira account/);
  assert.match(source, /Git identity/);
  assert.match(source, /GitHub login/);
  assert.match(preload, /epicSources:/);
  assert.match(preload, /connectEpicSharePoint:/);
  assert.match(preload, /epicReview:/);
  assert.match(preload, /runEpicChecks:/);
  assert.match(preload, /decideEpicReview:/);
  assert.match(preload, /completeEpicDelivery:/);
  assert.match(preload, /startEpicWizard:/);
  assert.match(preload, /startLocalEpic:/);
  assert.match(preload, /setExperienceMode:/);
  assert.match(preload, /openInitiative:/);
  assert.match(preload, /publishInitiativePhase:/);
  assert.match(preload, /approveInitiativePhase:/);
  assert.match(main, /epic:sources-upload/);
  assert.match(main, /epic:review-inbox/);
  assert.match(main, /epic:checks/);
  assert.match(main, /epic:decision/);
  assert.match(main, /epic:complete/);
  assert.match(main, /epic:start/);
  assert.match(main, /epic:start-local/);
  assert.match(main, /onboarding:experience/);
  assert.match(main, /initiative:open/);
  assert.match(main, /initiative:phase-publish/);
  assert.match(main, /initiative:phase-approve/);
  assert.match(main, /StorageCredentialStore/);
  assert.match(main, /authorizeSharePoint/);
  assert.match(source, /Sign in with Microsoft/);
  assert.match(source, /Approve exact packet/);
  assert.match(source, /Self-approval warning/);
  assert.match(source, /Story Work ID/);
  assert.match(source, /Create Jira & Git stories/);
  assert.match(source, /Question from Copilot/);
  assert.match(source, /Copilot logs/);
  assert.match(source, /Copilot backend/);
  assert.match(source, /Token usage by model/);
  assert.match(source, /Total tokens/);
  assert.match(source, /Apply model/);
  assert.match(source, /Connected/);
  assert.match(source, /Start backend/);
  assert.match(source, /Stop backend/);
  assert.match(source, /Planning context released; the Copilot backend remains ready/);
  assert.match(source, /Epic decomposition analysis/);
  assert.match(source, /Interface contracts/);
  assert.match(source, /Branches stay isolated/);
  assert.match(source, /never merges them into a default branch automatically/);
  assert.match(source, /No workspace selected/);
  assert.match(source, /lead repository/);
  assert.match(source, /Pending approvals/);
  assert.match(source, /Fetch remote inbox/);
  assert.match(source, /Model usage & cost/);
  assert.match(source, /Cost by phase/);
  assert.match(source, /Cost by model/);
  assert.match(source, /Cost needs telemetry or pricing/);
  assert.match(source, /Workflow time/);
  assert.match(source, /Total elapsed/);
  assert.match(source, /Approval waiting/);
  assert.match(source, /Copilot capture inactive/);
  assert.match(source, /Telemetry setup is outdated/);
  assert.match(source, /Waiting for Copilot export/);
  assert.match(source, /pending export/);
  assert.match(source, /No estimate shown/);
  assert.match(source, /Recent workspaces/);
  assert.match(source, /Workspace configuration/);
  assert.match(source, /Jira project key/);
  assert.match(source, /KAN from KAN-8/);
  assert.match(source, /Epic-level artifacts are committed here/);
  assert.match(source, /Review & save workspace/);
  assert.match(source, /Confirm & save workspace/);
  assert.match(source, /Complete: \$\{missingWorkspaceFields\.join\(', '\)\}/);
  assert.match(styles, /\.workspace-save-callout/);
  assert.doesNotMatch(navigation, /Initiative governance/);
  assert.doesNotMatch(navigation, /Jira connection/);
  assert.match(source, /Staged — not governed/);
  assert.match(source, /not separate setup steps/);
  assert.match(source, /Save workspace/);
  assert.match(source, /Isolated project contexts/);
  assert.doesNotMatch(source, /<RecentRepositories/);
  assert.doesNotMatch(source, /Open another repository/);
  assert.doesNotMatch(source, />Open repository</);
  assert.match(source, /Start with your/);
  assert.match(source, /label: 'Delivery'/);
  assert.match(source, /label: 'Decisions'/);
  assert.match(source, /label: 'Advanced'/);
  assert.match(source, /label: 'Configuration'/);
  assert.match(source, /label: 'Learn'/);
  assert.match(source, /label: 'Epic planning'/);
  assert.match(source, /\['business-requirements', 'Requirements'\]/);
  assert.match(source, /\['business-planning', 'Planning'\]/);
  assert.match(source, /\['templates', 'Artifact templates'\]/);
  assert.match(source, /\['business-stories', 'Create Stories'\]/);
  assert.match(source, /entryTab="requirements"/);
  assert.match(source, /entryTab="planning"/);
  assert.match(source, /entryTab="publish"/);
  assert.match(source, /Approved Story plan/);
  assert.match(source, /Jira Story key/);
  assert.match(source, /Canonical Git branch/);
  assert.match(source, /Commit templates/);
  assert.match(source, /Artifact builder/);
  assert.match(source, /Section library/);
  assert.match(source, /Drag into artifact/);
  assert.match(artifactBuilder, /Approved inputs/);
  assert.match(source, /Import from URL/);
  assert.match(source, /Fetch & preview/);
  assert.match(source, /Jira Story key/);
  assert.match(source, /context=\{data\.workspace \? data\.workspace\.workspace\.anchor\.key : 'Workspace'\}/);
  assert.match(source, /function FlowBrand/);
  assert.match(source, /className="flow-brand-parent">Singularity/);
  assert.match(source, /className="flow-brand-product">Flow/);
  assert.match(source, /aria-label=\{`Singularity Flow/);
  assert.match(indexHtml, /<title>Singularity Flow<\/title>/);
  assert.match(source, /singularity\.sidebar\.collapsed/);
  assert.match(source, /sidebar-collapsed/);
  assert.match(source, /sidebar-edge-toggle/);
  assert.match(source, /aria-controls="primary-navigation"/);
  assert.match(source, /function BusinessNavigation/);
  assert.match(source, /function WorkspaceSelector/);
  assert.match(source, /aria-label="Select current workspace"/);
  assert.match(source, /No workspace selected — choose one/);
  assert.match(source, /load its repositories, Jira routing, and complete project context/);
  assert.match(source, /Open or create workspace…/);
  assert.match(source, /className="business-navigation"/);
  assert.match(source, /aria-label="Epic planning navigation"/);
  assert.match(source, /experienceMode === 'business' \? 'business-shell'/);
  assert.match(source, /experienceMode === 'engineer' && <aside className="sidebar"/);
  assert.match(source, /Engineer tools/);
  assert.match(source, /event\.metaKey \|\| event\.ctrlKey/);
  assert.match(source, /event\.key\.toLowerCase\(\) !== 'b'/);
  assert.match(source, /className="page-stage"/);
  assert.match(source, /function NavIcon/);
  assert.match(source, /Artifact Studio/);
  assert.match(source, /Requirement workspace/);
  assert.match(source, /VisualComparisonReview/);
  assert.match(source, /Live design — may differ from the pinned intake/);
  assert.match(source, /Open in Figma/);
  assert.match(source, /Impact Analysis Studio/);
  assert.match(source, /Singularity intelligence/);
  assert.match(source, /Singularity analysis/);
  assert.doesNotMatch(source, /SDLC Planner/);
  assert.match(styles, /\.cost-dashboard/);
  assert.match(styles, /\.timing-dashboard/);
  assert.match(styles, /\.timing-row/);
  assert.match(styles, /\.cost-breakdown-grid/);
  assert.match(styles, /\.recent-repositories/);
  assert.match(styles, /\.workspace-health-grid/);
  assert.match(styles, /\.workspace-operation-list/);
  assert.match(styles, /\.initiative-flow/);
  assert.match(styles, /\.initiative-lanes/);
  assert.match(styles, /\.initiative-metrics/);
  assert.match(styles, /\.epic-progress-list/);
  assert.match(styles, /\.business-stage-intro/);
  assert.match(styles, /\.business-lineage-handoff/);
  assert.match(styles, /\.business-stage-intro \{ min-height: 112px/);
  assert.match(styles, /\.business-stage-intro h2/);
  assert.match(styles, /\.epic-start-intro \{ min-height: 128px/);
  assert.match(styles, /\.epic-start-flow span i/);
  assert.match(styles, /\.epic-start-flow span\.active i/);
  assert.match(styles, /\.epic-origin-choice button\.needs-setup/);
  assert.match(styles, /\.jira-setup-overlay/);
  assert.match(styles, /\.artifact-builder/);
  assert.match(styles, /\.artifact-section-palette/);
  assert.match(styles, /\.artifact-builder-canvas/);
  assert.match(styles, /\.artifact-section-card/);
  assert.match(styles, /\.artifact-drop-zone/);
  assert.match(styles, /\.remote-template-preview/);
  assert.match(styles, /\.copilot-question-card/);
  assert.match(styles, /\.planning-console/);
  assert.match(styles, /\.portfolio-setup/);
  assert.match(styles, /\.onboarding-shell/);
  assert.match(styles, /\.onboarding-progress/);
  assert.match(styles, /\.onboarding-ready-summary/);
  assert.match(styles, /\.onboarding-recovery/);
  assert.match(styles, /\.onboarding-failure/);
  assert.match(styles, /\.copilot-service-control/);
  assert.match(styles, /\.copilot-service-log/);
  assert.match(styles, /\.copilot-service-trigger\.stopped \{/);
  assert.match(styles, /\.copilot-service-trigger\.stopped \.copilot-service-orb/);
  assert.match(styles, /\.copilot-service-trigger\.stopped > i/);
  assert.match(styles, /\.repository-menu/);
  assert.match(styles, /\.studio-flow-track/);
  assert.match(styles, /\.requirement-layout/);
  assert.match(styles, /\.visual-comparison-review/);
  assert.match(styles, /\.comparison-slider/);
  assert.match(styles, /\.media-lightbox/);
  assert.match(styles, /\.pinned-media-strip/);
  assert.match(styles, /\.impact-graph/);
  assert.match(styles, /\.welcome-visual/);
  assert.match(styles, /\.flow-brand-mark/);
  assert.match(styles, /@keyframes flowOrbitPulse/);
  assert.match(styles, /\.flow-brand-parent/);
  assert.match(styles, /\.flow-brand-product/);
  assert.match(styles, /Avenir Next/);
  assert.match(styles, /--evergreen-950: #092d20/);
  assert.match(styles, /\.sidebar-edge-toggle/);
  assert.match(styles, /\.shell\.sidebar-collapsed \{ grid-template-columns: 72px/);
  assert.match(styles, /\.shell\.business-shell \{ grid-template-columns: minmax\(0,1fr\)/);
  assert.match(styles, /\.business-navigation/);
  assert.match(styles, /\.workspace-quick-selector/);
  assert.match(styles, /\.workspace-quick-control/);
  assert.match(styles, /\.business-project-switcher/);
  assert.match(styles, /\.business-shell \.topbar-title \{ display: none/);
  assert.match(styles, /Operational enterprise workspace/);
  assert.match(styles, /\.topbar-title/);
  assert.match(source, /className="topbar-title"/);
  assert.match(styles, /\.sidebar \{[\s\S]*background: #fff/);
  assert.match(styles, /\.workspace-command,[\s\S]*border: 1\.5px solid #65b783/);
  assert.match(styles, /Modern typography calibration/);
  assert.match(styles, /\.page-heading h1,[\s\S]*font-weight: 600/);
  assert.match(styles, /\.inbox-header,[\s\S]*font-weight: 540/);
  assert.doesNotMatch(styles, /#712ae2/i);
  assert.match(styles, /\.shell\.sidebar-collapsed/);
  assert.match(styles, /\.workflow-layout > \.design-pane/);
  assert.match(styles, /@keyframes page-arrive/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/);
  assert.match(preload, /recentRepositories/);
  assert.match(preload, /saveOnboarding/);
  assert.match(preload, /chooseOnboardingWorkspace/);
  assert.match(preload, /connectOnboardingJira/);
  assert.match(preload, /resetJiraCredentials/);
  assert.match(preload, /openRepository/);
  assert.match(preload, /forgetRepository/);
  assert.match(preload, /recentWorkspaces/);
  assert.match(preload, /previewWorkspaceConfiguration/);
  assert.match(preload, /previewTemplateUrl/);
  assert.match(preload, /createWorkspaceConfiguration/);
  assert.match(preload, /chooseWorkspaceRepositories/);
  assert.match(preload, /previewWorkspace/);
  assert.match(preload, /jiraWorkspaceAnchors/);
  assert.match(main, /repository:recent/);
  assert.match(main, /onboarding:get/);
  assert.match(main, /onboarding:save/);
  assert.match(main, /onboarding:jira-connect/);
  assert.match(main, /jira:reset-credentials/);
  assert.match(main, /function trustedHandle/);
  assert.equal((main.match(/\bipcMain\.handle\(/g) ?? []).length, 1);
  assert.match(main, /safeExternalUrl/);
  assert.match(main, /repository:open/);
  assert.match(main, /repository:forget/);
  assert.match(main, /workspace:create/);
  assert.match(main, /workspace:configuration-preview/);
  assert.match(main, /configuration:template-url-preview/);
  assert.match(main, /fetchRemoteMarkdown/);
  assert.match(main, /workspace:configuration-create/);
  assert.match(main, /workspace:repository-choose/);
  assert.match(main, /inspectWorkspaceSelection/);
  assert.match(main, /openWorkspaceSetup/);
  assert.match(main, /Choose the specific workspace folder/);
  assert.match(main, /workspace:documents-stage/);
  assert.match(main, /workspace:documents-promote/);
  assert.match(main, /staged-not-governed are excluded/);
  assert.match(main, /jira:workspace-anchors/);
  assert.match(preload, /promoteWorkspaceDocument/);
  assert.match(main, /copilotBackend\.stop\(activeRepository\)/);
  assert.match(main, /Migrate folder/);
  assert.match(main, /\['migrate-config'\]/);
  assert.match(main, /does not commit, push, merge, or rewrite Git history/);
  assert.match(preload, /deleteTemplate/);
  assert.match(preload, /refreshInbox/);
  assert.match(preload, /attachInboxItem/);
  assert.match(preload, /downloadFile/);
  assert.match(preload, /importFile/);
  assert.match(preload, /exportBundle/);
  assert.match(preload, /initiativeId/);
  assert.match(preload, /answerPlanningQuestion/);
  assert.match(preload, /bootstrapPortfolio/);
  assert.match(preload, /startCopilotService/);
  assert.match(preload, /setCopilotServiceModel/);
  assert.match(preload, /stopCopilotService/);
  assert.match(preload, /onCopilotServiceEvent/);
  assert.match(preload, /materializeInitiative/);
  assert.match(preload, /syncInitiative/);
  assert.match(main, /--initiative/);
  assert.match(main, /planning:answer/);
  assert.match(main, /configuration:bootstrap-portfolio/);
  assert.match(main, /copilot-service:start/);
  assert.match(main, /copilot-service:model/);
  assert.match(await readFile(path.join(packageRoot, 'apps', 'desktop', 'electron', 'copilot-acp.mjs'), 'utf8'), /session:\s*\{\s*configOptions:\s*\{\}\s*\}/);
  assert.match(main, /copilot-service:stop/);
  assert.match(main, /initiative:materialize/);
  assert.match(main, /\['documents', 'preview'/);
  assert.match(main, /Only HTTPS document links can be opened/);
  assert.match(source, /openDocument=\{openRequirementWorkspace\}/);
  assert.match(source, /Open in default app/);
  assert.doesNotMatch(source, /onClick=\{\(\) => document\.path \? downloadFile\(document\.path\) : openWorkspace\(\)\}/);
  assert.doesNotMatch(main, /figma\.com\/embed/);
  assert.doesNotMatch(main, /<webview>/);
});
