/** Visual workflow and artifact-template authoring for the VS Code extension. */
import {
  consequence, type Phase, type Profile, type Standing, type TemplateUsage
} from './designer-model.ts';
import {
  SECTION_CATALOG, newArtifactDraft, renderArtifactTemplate, type ArtifactDraft
} from './artifact-designer-model.ts';
import { escape, icon } from './webview.ts';

export type DesignerTab = 'phases' | 'templates';

export interface WorkflowDraftView {
  isNew: boolean;
  id: string;
  label: string;
  description: string;
  governs: 'story' | 'initiative';
  phases: Array<{ id: string; label: string }>;
}

export interface PhaseDraftView {
  isNew: boolean;
  id: string;
  label: string;
  governs: 'story' | 'initiative';
  views: string;
  agents: string;
  lanes: string;
}

export interface PhaseChoice {
  id: string;
  label: string;
  governs: 'story' | 'initiative';
}

function approvalSummary(approval: Phase['bundleApproval']): string {
  if (!approval) return '<span class="muted">No approval configured</span>';
  if (approval.chain?.length) {
    return `<ul class="chain">${approval.chain
      .map((step) => `<li>${escape(step.label ?? step.authority)}${step.minimum && step.minimum > 1 ? ` ×${step.minimum}` : ''}</li>`)
      .join('')}</ul>`;
  }
  const authorities = approval.authorities?.length ? approval.authorities.join(', ') : 'any configured identity';
  return `<span class="muted">${escape(approval.mode ?? 'individual')} · ${escape(authorities)}${approval.minimum && approval.minimum > 1 ? ` ×${approval.minimum}` : ''}</span>`;
}

function phaseHtml(phase: Phase, profileId: string): string {
  const generated = phase.outputs.filter((output) => output.generator);
  return `
  <article class="card">
    <div class="card-head">
      <span class="step-number">${phase.order + 1}</span>
      <div><h3>${escape(phase.label)}</h3><span class="muted"><code>${escape(phase.id)}</code></span></div>
      <span class="grow"></span>
      <span class="pill">${phase.outputs.length} ${phase.outputs.length === 1 ? 'artifact' : 'artifacts'}</span>
    </div>
    ${phase.outputs.length ? `
    <table>
      <thead><tr><th>Artifact</th><th>Policy</th><th>Template or generator</th><th>Approval</th></tr></thead>
      <tbody>${phase.outputs.map((output) => `
        <tr>
          <td>${icon('document')}<strong>${escape(output.label)}</strong><br><span class="muted"><code>${escape(output.id)}</code></span></td>
          <td>${output.required === false ? '<span class="muted">optional</span>' : '<span class="pill ok">required</span>'}</td>
          <td>${output.template
    ? `<button class="link" data-open-template="${escape(output.template)}">${escape(output.template)}</button>`
    : output.generator
      ? `<span class="muted">Generated by ${escape(output.generator)}</span>`
      : '<span class="muted">Not assigned</span>'}</td>
          <td>${approvalSummary(output.approval)}</td>
        </tr>`).join('')}</tbody>
    </table>` : '<p class="empty-state">This phase has no artifacts yet. Use Artifact designer to add one.</p>'}
    <div class="card-foot">
      <span class="muted">${generated.length ? `${generated.length} system-generated · ` : ''}${phase.checklist.length} checks</span>
      ${phase.bundleApproval ? `<span class="bundle-gate">Phase gate: ${approvalSummary(phase.bundleApproval)}</span>` : ''}
      <span class="grow"></span>
      <button class="link" data-edit-phase="${escape(phase.id)}" data-profile="${escape(profileId)}">Edit phase contract</button>
    </div>
  </article>`;
}

function workflowEditor(draft: WorkflowDraftView, choices: PhaseChoice[]): string {
  const available = choices.filter((phase) => phase.governs === draft.governs && !draft.phases.some((entry) => entry.id === phase.id));
  return `
  <section class="editor-card workflow-editor">
    <div class="editor-title">
      <p class="eyebrow">${draft.isNew ? 'New workflow' : 'Workflow settings'}</p>
      <h3>${draft.isNew ? 'Create an ordered delivery path' : `Edit ${escape(draft.label)}`}</h3>
      <p class="muted">The engine validates every phase reference before updating the governed YAML.</p>
    </div>
    <div class="form-grid">
      <label class="field"><span>Workflow ID</span><input data-workflow-id type="text" value="${escape(draft.id)}" ${draft.isNew ? '' : 'disabled'} placeholder="customer-onboarding"><small>Permanent lower-case identifier.</small></label>
      <label class="field"><span>Governs</span><select data-workflow-governs ${draft.isNew ? '' : 'disabled'}><option value="initiative"${draft.governs === 'initiative' ? ' selected' : ''}>Epic / Initiative</option><option value="story"${draft.governs === 'story' ? ' selected' : ''}>Developer Story</option></select><small>Determines which phase catalog is available.</small></label>
      <label class="field"><span>Display name</span><input data-workflow-label type="text" value="${escape(draft.label)}" placeholder="Customer onboarding"></label>
      <label class="field full"><span>Description</span><textarea data-workflow-description rows="3" placeholder="When should a team choose this workflow?">${escape(draft.description)}</textarea></label>
    </div>
    <h2>${icon('gate')}Phase sequence</h2>
    <div class="sequence-builder" data-workflow-sequence>
      ${draft.phases.length ? draft.phases.map((phase, index) => `
        <div class="sequence-row" data-workflow-phase="${escape(phase.id)}">
          <span class="step-number">${index + 1}</span><strong>${escape(phase.label)}</strong><code>${escape(phase.id)}</code><span class="grow"></span>
          <button class="icon-button" title="Move earlier" aria-label="Move ${escape(phase.label)} earlier" data-workflow-phase-action="up" data-index="${index}"${index === 0 ? ' disabled' : ''}>${icon('up')}</button>
          <button class="icon-button" title="Move later" aria-label="Move ${escape(phase.label)} later" data-workflow-phase-action="down" data-index="${index}"${index === draft.phases.length - 1 ? ' disabled' : ''}>${icon('down')}</button>
          <button class="icon-button danger" title="Remove phase" aria-label="Remove ${escape(phase.label)}" data-workflow-phase-action="remove" data-index="${index}">${icon('remove')}</button>
        </div>`).join('') : '<p class="empty-state">Add at least one phase to make this workflow runnable.</p>'}
    </div>
    <div class="add-row">
      <select data-workflow-add-phase><option value="">Choose a phase…</option>${available.map((phase) => `<option value="${escape(phase.id)}">${escape(phase.label)} — ${escape(phase.id)}</option>`).join('')}</select>
      <button class="secondary" data-add-workflow-phase="1"${available.length ? '' : ' disabled'}>Add phase</button>
    </div>
    <div class="form-actions"><button data-save-workflow="1">${draft.isNew ? 'Create workflow' : 'Save workflow'}</button><button class="secondary" data-cancel-workflow="1">Cancel</button></div>
  </section>`;
}

function phaseEditor(draft: PhaseDraftView): string {
  return `
  <section class="editor-card">
    <div class="editor-title"><p class="eyebrow">${draft.isNew ? 'New phase' : 'Phase contract'}</p><h3>${draft.isNew ? 'Define a reusable stage' : `Edit ${escape(draft.label)}`}</h3><p class="muted">${draft.isNew ? 'Creating a phase does not add it to a workflow. You choose its position afterwards.' : 'Changes reach every workflow that uses this phase.'}</p></div>
    <div class="form-grid">
      <label class="field"><span>Phase ID</span><input data-phase-id value="${escape(draft.id)}" ${draft.isNew ? '' : 'disabled'} placeholder="security-review"></label>
      <label class="field"><span>Display name</span><input data-phase-label value="${escape(draft.label)}" placeholder="Security review"></label>
      <label class="field"><span>Governs</span><select data-phase-governs ${draft.isNew ? '' : 'disabled'}><option value="initiative"${draft.governs === 'initiative' ? ' selected' : ''}>Epic / Initiative</option><option value="story"${draft.governs === 'story' ? ' selected' : ''}>Developer Story</option></select></label>
      <label class="field"><span>World-model views</span><input data-phase-views value="${escape(draft.views)}" placeholder="architecture,security"><small>Comma-separated repository views.</small></label>
      <label class="field"><span>Expected agents</span><input data-phase-agents value="${escape(draft.agents)}" placeholder="architect,security-reviewer"><small>Governed agents available in this repository.</small></label>
      <label class="field"><span>Business lanes</span><input data-phase-lanes value="${escape(draft.lanes)}" placeholder="design-architecture,engineering"><small>Initiative visualization only.</small></label>
    </div>
    <div class="form-actions"><button data-save-phase="1">${draft.isNew ? 'Create phase' : 'Save phase'}</button><button class="secondary" data-cancel-phase="1">Cancel</button></div>
  </section>`;
}

function phasesHtml(
  profiles: Profile[], selected: string | null, standing: Standing[], portfolioPath: string,
  draft: WorkflowDraftView | null, phaseDraft: PhaseDraftView | null, choices: PhaseChoice[]
): string {
  const profile = profiles.find((entry) => entry.id === selected) ?? profiles[0];
  if (!profile && !draft) return '<section class="empty-state"><h3>No workflow exists yet</h3><p>Create the first workflow from the phase catalog.</p><button data-new-workflow="1">Create workflow</button></section>';
  return `
  <section class="plain toolbar-row">
    ${profile ? `<label class="field compact"><span>Workflow</span><select data-profile-pick>${profiles.map((entry) => `<option value="${escape(entry.id)}"${entry.id === profile.id ? ' selected' : ''}>${escape(entry.label)} · ${entry.governs}</option>`).join('')}</select></label>` : ''}
    <span class="grow"></span>
    ${profile ? '<button class="secondary" data-edit-workflow="1">Edit workflow</button>' : ''}
    <button data-new-workflow="1">New workflow</button>
    <button class="secondary" data-new-phase="1">New phase</button>
  </section>
  ${draft ? workflowEditor(draft, choices) : ''}
  ${phaseDraft ? phaseEditor(phaseDraft) : ''}
  ${profile && !draft && !phaseDraft ? `
    <section class="workflow-summary">
      <div><p class="eyebrow">${escape(profile.governs)} workflow</p><h3>${escape(profile.label)}</h3><p class="muted">${escape(profile.description || 'No description yet.')}</p></div>
      <div class="workflow-rail">${profile.phases.map((phase, index) => `<span class="rail-node"><b>${index + 1}</b>${escape(phase.label)}</span>${index < profile.phases.length - 1 ? `<span class="rail-arrow">${icon('next')}</span>` : ''}`).join('')}</div>
      <p class="${standing.length ? 'blockers' : 'muted'}">${escape(consequence(standing, profile.governs === 'initiative' ? portfolioPath : 'singularity/workflow.yml'))}</p>
    </section>
    ${profile.phases.map((phase) => phaseHtml(phase, profile.id)).join('')}` : ''}
  <section class="plain raw-escape"><button class="link" data-open-file="${escape(profile?.governs === 'story' ? 'singularity/workflow.yml' : portfolioPath)}">Open governed YAML</button><span class="muted"> for advanced policies, conditional checks, and approval chains.</span></section>`;
}

function templateInventory(templates: TemplateUsage[], filter: string): string {
  const shown = filter === 'unused' ? templates.filter((entry) => !entry.usedBy.length)
    : filter === 'pinned' ? templates.filter((entry) => entry.standing.length) : templates;
  return `
  <section class="template-inventory">
    <div class="toolbar-row"><h2>${icon('document')}Template library</h2><span class="grow"></span><select data-template-filter><option value="all"${filter === 'all' ? ' selected' : ''}>All (${templates.length})</option><option value="pinned"${filter === 'pinned' ? ' selected' : ''}>Pinned (${templates.filter((entry) => entry.standing.length).length})</option><option value="unused"${filter === 'unused' ? ' selected' : ''}>Unused (${templates.filter((entry) => !entry.usedBy.length).length})</option></select></div>
    <div class="template-grid">${shown.length ? shown.map((template) => `<button class="template-tile" data-open-file="${escape(template.path)}"><strong>${escape(template.name)}</strong><span>${template.usedBy.length ? `${template.usedBy.length} uses` : 'Unused'}${template.standing.length ? ` · pinned by ${escape(template.standing.map((entry) => entry.id).join(', '))}` : ''}</span></button>`).join('') : '<p class="empty-state">No templates match this filter.</p>'}</div>
  </section>`;
}

function artifactPreview(draft: ArtifactDraft): string {
  return `<article class="document-preview"><p class="eyebrow">Live document preview</p><h1>${escape(draft.title || draft.outputLabel || 'Untitled artifact')}</h1><p>${escape(draft.purpose || 'Describe the purpose and decision this artifact supports.')}</p>${draft.sections.map((section) => `<section><h2>${escape(section.title)}</h2><p class="muted">${escape(section.guidance)}</p><div class="preview-placeholder">${escape(SECTION_CATALOG.find((entry) => entry.kind === section.kind)?.label ?? section.kind)} content</div></section>`).join('')}</article>`;
}

function artifactBuilder(draft: ArtifactDraft, profiles: Profile[], errors: string[]): string {
  const phases = profiles.flatMap((profile) => profile.phases.map((phase) => ({
    key: `${profile.governs}:${phase.id}`, profile: profile.label, governs: profile.governs, id: phase.id, label: phase.label
  }))).filter((entry, index, all) => all.findIndex((candidate) => candidate.key === entry.key) === index);
  return `
  <section class="artifact-studio">
    <div class="artifact-form editor-card">
      <div class="editor-title"><p class="eyebrow">Artifact template designer</p><h3>Build the document from sections</h3><p class="muted">The template and its phase wiring are saved together through the governance engine.</p></div>
      ${errors.length ? `<div class="blockers"><strong>Complete these fields</strong><ul>${errors.map((error) => `<li>${escape(error)}</li>`).join('')}</ul></div>` : ''}
      <div class="form-grid">
        <label class="field full"><span>Target phase</span><select data-artifact-phase><option value="">Choose a phase…</option>${phases.map((phase) => `<option value="${escape(phase.key)}"${draft.phaseId === phase.id && draft.governs === phase.governs ? ' selected' : ''}>${escape(phase.profile)} → ${escape(phase.label)} (${phase.governs})</option>`).join('')}</select></label>
        <label class="field"><span>Output ID</span><input data-artifact-output-id value="${escape(draft.outputId)}" placeholder="solution-architecture"><small>Stable traceability identifier.</small></label>
        <label class="field"><span>Artifact label</span><input data-artifact-output-label value="${escape(draft.outputLabel)}" placeholder="Solution architecture"></label>
        <label class="field"><span>Generated file</span><input data-artifact-output-path value="${escape(draft.outputPath)}" placeholder="solution-architecture.md"></label>
        <label class="field"><span>Template file</span><input data-artifact-file value="${escape(draft.fileName)}" placeholder="initiatives/solution-architecture.md"></label>
        <label class="field"><span>Document title</span><input data-artifact-title value="${escape(draft.title)}" placeholder="Solution Architecture"></label>
        <label class="field checkbox-field"><input type="checkbox" data-artifact-required${draft.required ? ' checked' : ''}><span>Required to complete this phase</span></label>
        <label class="field full"><span>Purpose</span><textarea data-artifact-purpose rows="3" placeholder="What decision does this document support?">${escape(draft.purpose)}</textarea></label>
      </div>
      <div class="toolbar-row"><h2>${icon('document')}Document sections</h2><span class="grow"></span><select data-section-kind>${SECTION_CATALOG.map((entry) => `<option value="${entry.kind}">${escape(entry.label)} — ${escape(entry.description)}</option>`).join('')}</select><button class="secondary" data-add-section="1">Add section</button></div>
      <div class="section-canvas" data-section-canvas>${draft.sections.map((section, index) => `
        <div class="section-block" draggable="true" data-section-index="${index}" data-section-kind="${section.kind}">
          <span class="drag-handle" title="Drag to reorder" role="img" aria-label="Drag ${escape(section.title)} to reorder">${icon('drag')}</span>
          <div class="section-fields"><input data-section-title value="${escape(section.title)}" aria-label="Section heading"><textarea data-section-guidance rows="2" aria-label="Section guidance">${escape(section.guidance)}</textarea><span class="muted">${escape(SECTION_CATALOG.find((entry) => entry.kind === section.kind)?.label ?? section.kind)}</span></div>
          <div class="section-actions"><button class="icon-button" title="Move section earlier" aria-label="Move ${escape(section.title)} earlier" data-section-action="up" data-index="${index}"${index === 0 ? ' disabled' : ''}>${icon('up')}</button><button class="icon-button" title="Move section later" aria-label="Move ${escape(section.title)} later" data-section-action="down" data-index="${index}"${index === draft.sections.length - 1 ? ' disabled' : ''}>${icon('down')}</button><button class="icon-button danger" title="Remove section" aria-label="Remove ${escape(section.title)}" data-section-action="remove" data-index="${index}">${icon('remove')}</button></div>
        </div>`).join('')}</div>
      <details><summary>Markdown that will be committed</summary><pre class="markdown-preview">${escape(renderArtifactTemplate(draft))}</pre></details>
      <div class="form-actions"><button data-save-artifact="1">Save template and wire artifact</button><button class="secondary" data-reset-artifact="1">Reset</button></div>
    </div>
    ${artifactPreview(draft)}
  </section>`;
}

export function designerHtml(
  tab: DesignerTab, profiles: Profile[], templates: TemplateUsage[], selectedProfile: string | null,
  filter: string, standing: Standing[], portfolioPath: string, error: string | null,
  workflowDraft: WorkflowDraftView | null = null, phaseDraft: PhaseDraftView | null = null,
  artifactDraft: ArtifactDraft = newArtifactDraft(), artifactErrors: string[] = [], phaseChoices: PhaseChoice[] = []
): string {
  return `
  <header><p class="eyebrow">Workflow designer · configuration studio</p><h1>${icon('workflow', { size: 20 })}Workflows & artifacts</h1><p class="meta">Create the delivery path and design the documents each phase must produce. Every save is validated by the same engine used by the CLI.</p></header>
  ${error ? `<section class="plain"><div class="blockers">${escape(error)}</div></section>` : ''}
  <nav class="designer-tabs" aria-label="Configuration designers"><button class="tab${tab === 'phases' ? ' active' : ''}" aria-current="${tab === 'phases' ? 'page' : 'false'}" data-tab="phases">${icon('workflow')}Workflow builder</button><button class="tab${tab === 'templates' ? ' active' : ''}" aria-current="${tab === 'templates' ? 'page' : 'false'}" data-tab="templates">${icon('artifact')}Artifact designer</button></nav>
  ${tab === 'phases'
    ? phasesHtml(profiles, selectedProfile, standing, portfolioPath, workflowDraft, phaseDraft, phaseChoices)
    : `${artifactBuilder(artifactDraft, profiles, artifactErrors)}${templateInventory(templates, filter)}`}`;
}

export const DESIGNER_SCRIPT = `
  const vscode = window.__sfVscode;
  const value = (selector) => document.querySelector(selector)?.value?.trim() ?? '';
  const sections = () => [...document.querySelectorAll('[data-section-index]')].map((row) => ({
    kind: row.dataset.sectionKind,
    title: row.querySelector('[data-section-title]')?.value ?? '',
    guidance: row.querySelector('[data-section-guidance]')?.value ?? ''
  }));
  const workflowFields = () => ({
    id: value('[data-workflow-id]'),
    label: value('[data-workflow-label]'),
    description: value('[data-workflow-description]'),
    governs: document.querySelector('[data-workflow-governs]')?.value
  });
  const artifactFields = () => ({
    phase: document.querySelector('[data-artifact-phase]')?.value,
    outputId: value('[data-artifact-output-id]'),
    outputLabel: value('[data-artifact-output-label]'),
    outputPath: value('[data-artifact-output-path]'),
    fileName: value('[data-artifact-file]'),
    title: value('[data-artifact-title]'),
    purpose: value('[data-artifact-purpose]'),
    required: Boolean(document.querySelector('[data-artifact-required]')?.checked),
    sections: sections()
  });
  document.addEventListener('click', (event) => {
    const target = event.target.closest('button[data-tab],button[data-open-file],button[data-open-template],button[data-edit-phase],button[data-edit-workflow],button[data-new-workflow],button[data-new-phase],button[data-cancel-workflow],button[data-save-workflow],button[data-workflow-phase-action],button[data-add-workflow-phase],button[data-save-phase],button[data-cancel-phase],button[data-add-section],button[data-section-action],button[data-save-artifact],button[data-reset-artifact]');
    if (!target) return;
    event.preventDefault();
    const data = target.dataset;
    if (data.tab) vscode.postMessage({ type: 'tab', tab: data.tab });
    else if (data.openFile) vscode.postMessage({ type: 'open', path: data.openFile });
    else if (data.openTemplate) vscode.postMessage({ type: 'open-template', template: data.openTemplate });
    else if (data.editPhase) vscode.postMessage({ type: 'edit-phase', phase: data.editPhase });
    else if (data.editWorkflow !== undefined) vscode.postMessage({ type: 'begin-workflow' });
    else if (data.newWorkflow !== undefined) vscode.postMessage({ type: 'new-workflow' });
    else if (data.newPhase !== undefined) vscode.postMessage({ type: 'new-phase' });
    else if (data.cancelWorkflow !== undefined) vscode.postMessage({ type: 'cancel-workflow' });
    else if (data.workflowPhaseAction) vscode.postMessage({ type: 'workflow-phase-action', action: data.workflowPhaseAction, index: Number(data.index), ...workflowFields() });
    else if (data.addWorkflowPhase !== undefined) vscode.postMessage({ type: 'add-workflow-phase', phase: value('[data-workflow-add-phase]'), ...workflowFields() });
    else if (data.saveWorkflow !== undefined) vscode.postMessage({ type: 'save-workflow', ...workflowFields() });
    else if (data.savePhase !== undefined) vscode.postMessage({ type: 'save-phase', id: value('[data-phase-id]'), label: value('[data-phase-label]'), governs: document.querySelector('[data-phase-governs]')?.value, views: value('[data-phase-views]'), agents: value('[data-phase-agents]'), lanes: value('[data-phase-lanes]') });
    else if (data.cancelPhase !== undefined) vscode.postMessage({ type: 'cancel-phase' });
    else if (data.addSection !== undefined) vscode.postMessage({ type: 'artifact-sections', action: 'add', kind: document.querySelector('[data-section-kind]')?.value, ...artifactFields() });
    else if (data.sectionAction) vscode.postMessage({ type: 'artifact-sections', action: data.sectionAction, index: Number(data.index), ...artifactFields() });
    else if (data.resetArtifact !== undefined) vscode.postMessage({ type: 'reset-artifact' });
    else if (data.saveArtifact !== undefined) vscode.postMessage({ type: 'save-artifact', ...artifactFields() });
  });
  document.addEventListener('change', (event) => {
    const pick = event.target.dataset;
    if (pick?.profilePick !== undefined) vscode.postMessage({ type: 'profile', id: event.target.value });
    else if (pick?.templateFilter !== undefined) vscode.postMessage({ type: 'filter', value: event.target.value });
    else if (pick?.workflowGoverns !== undefined) vscode.postMessage({ type: 'workflow-governs', value: event.target.value, ...workflowFields() });
    else if (pick?.artifactPhase !== undefined) vscode.postMessage({ type: 'artifact-phase', value: event.target.value, ...artifactFields() });
  });
  let dragged = null;
  document.addEventListener('dragstart', (event) => { const row = event.target.closest('[data-section-index]'); if (row) dragged = Number(row.dataset.sectionIndex); });
  document.addEventListener('dragover', (event) => { if (event.target.closest('[data-section-index]')) event.preventDefault(); });
  document.addEventListener('drop', (event) => { const row = event.target.closest('[data-section-index]'); if (!row || dragged == null) return; event.preventDefault(); vscode.postMessage({ type: 'artifact-sections', action: 'move', index: dragged, to: Number(row.dataset.sectionIndex), ...artifactFields() }); dragged = null; });
  document.addEventListener('input', () => {
    const preview = document.querySelector('.document-preview');
    if (!preview) return;
    const heading = preview.querySelector('h1');
    const purpose = preview.querySelector(':scope > p:not(.eyebrow)');
    if (heading) heading.textContent = value('[data-artifact-title]') || value('[data-artifact-output-label]') || 'Untitled artifact';
    if (purpose) purpose.textContent = value('[data-artifact-purpose]') || 'Describe the purpose and decision this artifact supports.';
    [...preview.querySelectorAll(':scope > section')].forEach((section, index) => {
      const source = document.querySelector('[data-section-index="' + index + '"]');
      const title = section.querySelector('h2');
      const guide = section.querySelector('p');
      if (title && source) title.textContent = source.querySelector('[data-section-title]')?.value ?? '';
      if (guide && source) guide.textContent = source.querySelector('[data-section-guidance]')?.value ?? '';
    });
  });
`;
