/**
 * The designer's markup: the lifecycle on one tab, the templates it draws from on the other.
 *
 * Both tabs lead with the same fact, because it is the one the files cannot tell you — which
 * running Epics pinned the thing you are about to edit, and would therefore stop rather than change.
 */
import {
  consequence, type Phase, type Profile, type Standing, type TemplateUsage
} from './designer-model.ts';
import { escape, icon } from './webview.ts';

export type DesignerTab = 'phases' | 'templates';

function approvalSummary(approval: Phase['bundleApproval']): string {
  if (!approval) return '<span class="muted">—</span>';
  if (approval.chain?.length) {
    return `<ul class="chain">${approval.chain
      .map((step) => `<li>${escape(step.label ?? step.authority)}${step.minimum && step.minimum > 1 ? ` ×${step.minimum}` : ''}</li>`)
      .join('')}</ul>`;
  }
  const authorities = approval.authorities?.length ? approval.authorities.join(', ') : 'anyone';
  return `<span class="muted">${escape(approval.mode ?? 'individual')} · ${escape(authorities)}${approval.minimum && approval.minimum > 1 ? ` ×${approval.minimum}` : ''}</span>`;
}

function phaseHtml(phase: Phase, profileId: string): string {
  const authored = phase.outputs.filter((output) => output.template);
  const generated = phase.outputs.filter((output) => output.generator);
  return `
  <article class="card">
    <div class="card-head">
      <h3>${icon('gate')}${escape(phase.label)}</h3>
      <span class="muted">${escape(phase.id)}</span>
      <span class="grow"></span>
      <span class="muted">${phase.outputs.length} ${phase.outputs.length === 1 ? 'artifact' : 'artifacts'}${generated.length ? `, ${generated.length} generated` : ''}</span>
    </div>

    ${phase.outputs.length ? `
    <table>
      <thead><tr><th>Artifact</th><th>Required</th><th>Starts from</th><th>Approval</th></tr></thead>
      <tbody>${phase.outputs.map((output) => `
        <tr>
          <td>${icon('document')}${escape(output.label)}<br><span class="muted">${escape(output.id)}</span></td>
          <td>${output.required
    ? `<span class="pill ok">${icon('ok')}required</span>`
    : '<span class="muted">optional</span>'}</td>
          <td>${output.template
    ? `<button class="link" data-open-template="${escape(output.template)}">${escape(output.template.split('/').at(-1) ?? output.template)}</button>`
    : output.generator
      ? `<span class="muted">generated by ${escape(output.generator)}</span>`
      : '<span class="muted">—</span>'}</td>
          <td>${approvalSummary(output.approval)}</td>
        </tr>`).join('')}</tbody>
    </table>` : '<p class="muted">This phase produces no artifacts.</p>'}

    ${phase.bundleApproval ? `
    <p class="muted">Closing the phase: ${approvalSummary(phase.bundleApproval)}</p>` : ''}
    ${phase.checklist.length ? `
    <p class="muted">${phase.checklist.length} checklist ${phase.checklist.length === 1 ? 'item' : 'items'}: ${phase.checklist.slice(0, 4).map((item) => escape(item.label ?? item.id)).join(', ')}${phase.checklist.length > 4 ? '…' : ''}</p>` : ''}

    <p class="card-foot">
      <button class="link" data-edit-phase="${escape(phase.id)}" data-profile="${escape(profileId)}">Edit this phase</button>
      <span class="muted">${authored.length} of ${phase.outputs.length} start from a template</span>
    </p>
  </article>`;
}

function phasesHtml(profiles: Profile[], selected: string | null, standing: Standing[], portfolioPath: string): string {
  const profile = profiles.find((entry) => entry.id === selected) ?? profiles[0];
  if (!profile) return '<p class="muted">This repository declares no delivery profiles.</p>';

  return `
  <section class="plain">
    <p>
      <label>Profile <select data-profile-pick>
        ${profiles.map((entry) => `<option value="${escape(entry.id)}"${entry.id === profile.id ? ' selected' : ''}>${escape(entry.label)} — ${entry.phases.length} phases</option>`).join('')}
      </select></label>
    </p>
    <ul class="chain">${profile.phases.map((phase) => `<li>${escape(phase.label)}</li>`).join('')}</ul>
    <p class="${standing.length ? 'blockers' : 'muted'}">${escape(consequence(standing, portfolioPath))}</p>
    <p>
      <button class="secondary" data-reorder="1">Change which phases this workflow runs</button>
      <button class="secondary" data-new-profile="1">New workflow</button>
      <button class="secondary" data-new-phase="1">New phase</button>
    </p>
    <p class="muted">A workflow is an ordered list of phases; a phase is what that stage produces
      and who signs it off. Changing either is governed configuration, so it is written through the
      engine and validated before it lands.</p>
    <p><button class="secondary" data-open-file="${escape(portfolioPath)}">Edit ${escape(portfolioPath)}</button></p>
  </section>

  ${profile.phases.map((phase) => phaseHtml(phase, profile.id)).join('')}`;
}

function templatesHtml(templates: TemplateUsage[], filter: string): string {
  const shown = filter === 'unused'
    ? templates.filter((template) => !template.usedBy.length)
    : filter === 'pinned'
      ? templates.filter((template) => template.standing.length)
      : templates;

  return `
  <section class="plain">
    <p>
      <label>Show <select data-template-filter>
        <option value="all"${filter === 'all' ? ' selected' : ''}>All ${templates.length}</option>
        <option value="pinned"${filter === 'pinned' ? ' selected' : ''}>Pinned by a running Epic (${templates.filter((entry) => entry.standing.length).length})</option>
        <option value="unused"${filter === 'unused' ? ' selected' : ''}>Used by nothing (${templates.filter((entry) => !entry.usedBy.length).length})</option>
      </select></label>
    </p>
    <p class="muted">A template nothing points at is either about to be wired up or dead, and only a
      person can tell which — so it is listed rather than hidden.</p>
  </section>

  <section>
    ${shown.length ? `
    <table>
      <thead><tr><th>Template</th><th>Used by</th><th>Pinned by</th><th></th></tr></thead>
      <tbody>${shown.map((template) => `
        <tr${template.standing.length ? ' class="drift"' : ''}>
          <td>${icon('document')}<code>${escape(template.name)}</code></td>
          <td class="muted">${template.usedBy.length
    ? template.usedBy.slice(0, 3).map((use) => `${escape(use.phase)}/${escape(use.output)}`).join(', ') + (template.usedBy.length > 3 ? ` +${template.usedBy.length - 3}` : '')
    : '<span class="pill">nothing</span>'}</td>
          <td>${template.standing.length
    ? `<span class="pill bad">${icon('bad')}${template.standing.map((entry) => escape(entry.id)).join(', ')}</span>`
    : '<span class="muted">—</span>'}</td>
          <td><button class="link" data-open-file="${escape(template.path)}">Open</button></td>
        </tr>`).join('')}</tbody>
    </table>` : '<p class="muted">Nothing matches that filter.</p>'}
  </section>

  <section>
    <h2>${icon('document')}New template</h2>
    <p>
      <label>File name <input type="text" data-new-template placeholder="release-checklist.md" size="30"></label>
      <button class="secondary" data-create-template="1">Create</button>
    </p>
    <p class="muted">Created with the section shape the existing artifacts use — a statement of what
      the document is for, tables with stable identifiers, open questions, and an evidence section.
      Point a phase output at it in <code>portfolio.yml</code> to put it into a lifecycle.</p>
  </section>`;
}

export function designerHtml(
  tab: DesignerTab,
  profiles: Profile[],
  templates: TemplateUsage[],
  selectedProfile: string | null,
  filter: string,
  standing: Standing[],
  portfolioPath: string,
  error: string | null
): string {
  return `
  <header>
    <h1>${icon('gate', { size: 20 })}Workflow designer</h1>
    <p class="meta">The phases a profile runs, the artifacts each produces, and the templates they
      start from. An Epic pins all of this when it starts, so an edit here reaches the next Epic —
      not the ones already running.</p>
  </header>

  ${error ? `<section class="plain"><p class="blockers">${escape(error)}</p></section>` : ''}

  <section class="plain">
    <p class="card-foot">
      <button class="${tab === 'phases' ? '' : 'secondary'}" data-tab="phases">Phases</button>
      <button class="${tab === 'templates' ? '' : 'secondary'}" data-tab="templates">Artifact templates</button>
    </p>
  </section>

  ${tab === 'phases'
    ? phasesHtml(profiles, selectedProfile, standing, portfolioPath)
    : templatesHtml(templates, filter)}`;
}

export const DESIGNER_SCRIPT = `
  const vscode = acquireVsCodeApi();
  document.addEventListener('click', (event) => {
    const target = event.target.closest('[data-tab],[data-open-file],[data-open-template],[data-edit-phase],[data-create-template],[data-reorder],[data-new-profile],[data-new-phase]');
    if (!target) return;
    event.preventDefault();
    const data = target.dataset;
    if (data.tab) vscode.postMessage({ type: 'tab', tab: data.tab });
    else if (data.openFile) vscode.postMessage({ type: 'open', path: data.openFile });
    else if (data.openTemplate) vscode.postMessage({ type: 'open-template', template: data.openTemplate });
    else if (data.editPhase) vscode.postMessage({ type: 'edit-phase', phase: data.editPhase });
    else if (data.reorder) vscode.postMessage({ type: 'reorder-phases' });
    else if (data.newProfile) vscode.postMessage({ type: 'new-profile' });
    else if (data.newPhase) vscode.postMessage({ type: 'new-phase' });
    else if (data.createTemplate) {
      const name = document.querySelector('[data-new-template]');
      if (name && name.value.trim()) vscode.postMessage({ type: 'create-template', name: name.value.trim() });
    }
  });
  document.addEventListener('change', (event) => {
    const pick = event.target.dataset;
    if (pick?.profilePick !== undefined) vscode.postMessage({ type: 'profile', id: event.target.value });
    else if (pick?.templateFilter !== undefined) vscode.postMessage({ type: 'filter', value: event.target.value });
  });
`;
