import path from 'node:path';

const DEFAULT_RUNTIME_ROOTS = Object.freeze([
  'singularity/initiatives',
  'singularity/work-items',
  'singularity/seeds',
  'singularity/world-model',
  'singularity/knowledge',
  'singularity/pins',
  'singularity/identity-reservations',
  'singularity/sgos-drafts',
  'singularity/telemetry',
  'singularity/.product'
]);

function invalidRoot(label, value) {
  const error = new Error(`${label} must be a canonical repository-relative portable path: ${value}`);
  error.name = 'SingularityFlowError';
  error.code = 'CONFIGURATION_ASSET_ROOT_INVALID';
  return error;
}

function portablePath(value, label) {
  const candidate = String(value ?? '').trim();
  if (!candidate || candidate.includes('\0') || candidate.includes('\\')
      || path.posix.isAbsolute(candidate) || path.win32.isAbsolute(candidate)
      || path.posix.normalize(candidate) !== candidate
      || candidate === '.' || candidate.endsWith('/')
      || candidate.split('/').includes('..')
      || candidate === '.git' || candidate.startsWith('.git/')) {
    throw invalidRoot(label, value);
  }
  return candidate;
}

function unique(values) {
  return [...new Set(values.filter(Boolean))].sort();
}

/**
 * Build the one bounded path policy used to transport and mount approved configuration.
 *
 * `singularity/` remains the conventional policy root, but its runtime children are excluded.
 * Generated world-model output remains runtime state even when the repository chooses a custom
 * destination. It is published and reconciled independently on the state branch; treating that
 * destination as configuration would copy generated bytes into Story branches and let a
 * configuration refresh overwrite the independently published model.
 */
export function configurationAssetPolicy(workflow = {}, portfolio = {}) {
  const configuredWorldModelRoot = portablePath(
    workflow.worldModel?.outputDir ?? 'singularity/world-model', 'worldModel.outputDir'
  );
  const roots = unique([
    portablePath(workflow.templatesRoot ?? 'singularity/templates', 'templatesRoot'),
    portablePath(workflow.agentPromptsRoot ?? '.github/agents', 'agentPromptsRoot'),
    portablePath(portfolio.templatesRoot ?? workflow.templatesRoot ?? 'singularity/templates',
      'portfolio.templatesRoot')
  ]);
  const files = unique([
    workflow.worldModel?.promptSource && workflow.worldModel.promptSource !== 'builtin'
      ? portablePath(workflow.worldModel.promptSource, 'worldModel.promptSource')
      : null
  ]);
  const runtimeRoots = unique([
    ...DEFAULT_RUNTIME_ROOTS,
    configuredWorldModelRoot,
    workflow.workItemRoot
      ? portablePath(workflow.workItemRoot, 'workItemRoot')
      : 'singularity/work-items',
    portfolio.initiativeRoot
      ? portablePath(portfolio.initiativeRoot, 'portfolio.initiativeRoot')
      : 'singularity/initiatives'
  ]);
  return Object.freeze({
    roots: Object.freeze(roots),
    files: Object.freeze(files),
    runtimeRoots: Object.freeze(runtimeRoots)
  });
}

export function mergeConfigurationAssetPolicies(...policies) {
  return Object.freeze({
    roots: Object.freeze(unique(policies.flatMap((policy) => policy?.roots ?? []))),
    files: Object.freeze(unique(policies.flatMap((policy) => policy?.files ?? []))),
    runtimeRoots: Object.freeze(unique(policies.flatMap((policy) => policy?.runtimeRoots ?? [])))
  });
}

export const DEFAULT_CONFIGURATION_ASSET_POLICY = configurationAssetPolicy();

function within(relative, root) {
  return relative === root || relative.startsWith(`${root}/`);
}

export function portableConfigurationPath(value) {
  const relative = String(value ?? '').replace(/^\.\//, '');
  if (!relative || relative.includes('\0') || relative.includes('\\')
      || path.posix.isAbsolute(relative) || path.win32.isAbsolute(relative)
      || path.posix.normalize(relative) !== relative || relative.split('/').includes('..')
      || relative === '.git' || relative.startsWith('.git/')) return null;
  return relative;
}

export function isConfigurationAssetPath(value, policy = DEFAULT_CONFIGURATION_ASSET_POLICY) {
  const relative = portableConfigurationPath(value);
  if (!relative || relative === 'singularity/configuration-source.json') return false;
  // Runtime ownership is the stronger boundary. In particular, a custom world-model output must
  // never become configuration merely because it is nested under a configured template/agent root.
  if (policy.runtimeRoots.some((root) => within(relative, root))) return false;
  if (policy.files.includes(relative) || policy.roots.some((root) => within(relative, root))) return true;
  if (!within(relative, 'singularity')) return false;
  return true;
}

/** Bounded Git/path-walk roots; never collapse custom roots into the repository root. */
export function configurationAssetSearchRoots(policy = DEFAULT_CONFIGURATION_ASSET_POLICY) {
  return unique([
    'singularity',
    ...policy.roots.filter((root) => !within(root, 'singularity')),
    ...policy.files.filter((file) => !within(file, 'singularity'))
  ]);
}
