import path from 'node:path';
import { readFile } from 'node:fs/promises';
import YAML from 'yaml';
import { run, commandExists, exists, SingularityFlowError } from './util.mjs';
import { githubAuthStatus } from './github-evidence.mjs';

// Where the story's pull request goes. Materialization records the branch the story was cut from;
// for a story in the epic's own repository that is the epic branch, so the pull request targets the
// epic branch and the epic lands on the default branch once every blocking story has merged.
export function pullRequestTarget(workflow, seed = null) {
  const base = seed?.story?.parentBranch
    ?? workflow.workItem.baseBranch
    ?? 'main';
  return { base, head: workflow.workItem.branch ?? workflow.workItem.id };
}

function bulleted(values, empty) {
  const items = (values ?? []).filter(Boolean);
  return items.length ? items.map((item) => `- ${item}`).join('\n') : `_${empty}_`;
}

// A pull-request body assembled entirely from committed, governed state: the epic and story
// identity, the acceptance criteria, and every approved artifact with the exact hash it was
// approved at. Nothing here is invented.
export function storyPullRequestBody(workflow, seed = null, { mergeSequence = null } = {}) {
  const story = seed?.story ?? {};
  const initiative = seed?.initiative ?? {};
  const lines = [];

  lines.push(`## ${workflow.workItem.id} — ${workflow.workItem.title}`, '');
  if (story.description) lines.push(story.description, '');

  lines.push('### Lineage', '');
  if (initiative.id) lines.push(`- Epic: \`${initiative.id}\`${story.epicJiraKey ? ` (Jira ${story.epicJiraKey})` : ''}`);
  if (initiative.branch) lines.push(`- Epic branch: \`${initiative.branch}\``);
  if (story.jiraKey) lines.push(`- Story: Jira ${story.jiraKey}`);
  if (story.parentBranch) lines.push(`- Branched from: \`${story.parentBranch}\`${story.baseCommit ? ` at \`${story.baseCommit.slice(0, 8)}\`` : ''}`);
  lines.push(`- Work type: \`${workflow.workItem.workType}\``, '');

  lines.push('### Acceptance criteria', '', bulleted(story.acceptanceCriteria, 'None recorded in the story seed.'), '');

  const artifacts = seed?.approvedArtifacts ?? [];
  lines.push('### Approved epic artifacts', '');
  lines.push(artifacts.length
    ? artifacts.map((item) => `- \`${item.path}\` — ${item.phase}/${item.output} @ \`${String(item.sha256).slice(0, 12)}\``).join('\n')
    : '_No approved epic artifacts were recorded._');
  lines.push('');

  const checks = story.requiredChecks ?? [];
  if (checks.length) lines.push('### Required checks', '', bulleted(checks, ''), '');

  if (mergeSequence) {
    const entry = mergeSequence.stories?.find((item) => item.workId === workflow.workItem.id || item.id === workflow.workItem.id);
    if (entry) {
      lines.push('### Merge sequence', '');
      lines.push(`- Position ${entry.order} of ${mergeSequence.stories.length}${entry.blocking ? ' (blocking)' : ''}`);
      if (entry.blockedBy?.length) lines.push(`- Blocked by: ${entry.blockedBy.join(', ')}`);
      lines.push('');
    }
  }

  lines.push('---', '', 'Generated by Singularity Flow from committed workflow state.');
  return lines.join('\n');
}

export async function readStorySeed(root, workflow) {
  const relative = workflow.source?.seed ?? path.posix.join('singularity', 'seeds', `${workflow.workItem.id}.yml`);
  const absolute = path.join(root, relative);
  if (!(await exists(absolute))) return null;
  try { return YAML.parse(await readFile(absolute, 'utf8')); }
  catch { throw new SingularityFlowError(`Story seed ${relative} is not valid YAML.`); }
}

// Build the complete pull request without contacting GitHub. Always safe to run.
export async function storyPullRequestPlan(root, config, workflow, { mergeSequence = null } = {}) {
  const seed = await readStorySeed(root, workflow);
  const { base, head } = pullRequestTarget(workflow, seed);
  const policy = seed?.story?.branchCompletionPolicy ?? workflow.source?.branchCompletionPolicy ?? 'pr';
  if (policy === 'direct') {
    throw new SingularityFlowError(`Repository policy for ${workflow.workItem.id} is 'direct'; it does not use pull requests.`);
  }
  if (base === head) throw new SingularityFlowError(`Pull request base and head are both '${base}'.`);
  return {
    workId: workflow.workItem.id,
    base,
    head,
    policy,
    title: `${workflow.workItem.id}: ${workflow.workItem.title}`,
    body: storyPullRequestBody(workflow, seed, { mergeSequence }),
    requiredChecks: seed?.story?.requiredChecks ?? [],
    blockedBy: mergeSequence?.stories?.find((item) => item.workId === workflow.workItem.id)?.blockedBy ?? []
  };
}

// Create the pull request. Outward action: callers must obtain explicit confirmation first.
export function createStoryPullRequest(root, plan, { remote = 'origin', runCommand = run } = {}) {
  if (plan.blockedBy.length) {
    throw new SingularityFlowError(`${plan.workId} cannot open a pull request yet: ${plan.blockedBy.join(', ')} must merge into ${plan.base} first.`);
  }
  if (runCommand === run && !commandExists('gh')) {
    throw new SingularityFlowError('Opening a pull request requires the GitHub CLI. Install gh and run gh auth login, or open the pull request manually using the generated body.');
  }
  const url = runCommand('git', ['remote', 'get-url', remote], { cwd: root, allowFailure: true });
  if (url.status !== 0) throw new SingularityFlowError(`Remote '${remote}' is not configured.`);
  githubAuthStatus(root, url.stdout.trim(), { runCommand });

  const existing = runCommand('gh', ['pr', 'list', '--head', plan.head, '--base', plan.base, '--json', 'url', '--jq', '.[0].url'], { cwd: root, allowFailure: true });
  if (existing.status === 0 && existing.stdout.trim()) {
    return { status: 'existing', url: existing.stdout.trim(), base: plan.base, head: plan.head };
  }
  const created = runCommand('gh', ['pr', 'create', '--base', plan.base, '--head', plan.head, '--title', plan.title, '--body', plan.body], { cwd: root, allowFailure: true });
  if (created.status !== 0) throw new SingularityFlowError(`Unable to open the pull request: ${(created.stderr || created.stdout).trim()}`);
  return { status: 'created', url: created.stdout.trim().split(/\s+/).pop(), base: plan.base, head: plan.head };
}
